### ISSUE TITLE
is_sampled is no longer exported in index.d.ts

### ISSUE THREAD

**Issue by Sibirius** [maraisr/trcprnt#4]
### Describe the bug

Thank you so much for the quick release of `0.0.11` @maraisr  🙏 
Unfortunately this now breaks the `is_sampled` functionality that we were already using.

In the released version `0.0.11` the function `is_sampled`  is no longer exported in `index.d.ts` which was available in `0.0.10`.
This happened when switching to building with bundt in ec5df708f9e044095f39f365f5161b1c2a1a6a11.
You can see the diff here: https://diff.intrinsic.com/tctx/0.0.10/0.0.11#file-index.d.ts

Not sure if this was an intended change, if so please disregard this issue. But it would be great not having to implement the flag checking myself.

### To reproduce

Install `0.0.11` and try to import `is_sampled`

### Expected behavior

`is_sampled` can be imported from `tctx`. I would also be fine with it being directly available on the `Traceparent` interface if you want to keep the api small.

**Comment by maraisr** [comment]
Hi @Sibirius  thank you so much for the issue, apologies for that. I have fixed the issue and published this under v0.0.12.
